### ISSUE TITLE
Problems in version 2

### ISSUE THREAD

**Issue by umangapathak999** [awcodes/curator#3]
```
composer require awcodes/curator
```
This command does not work at the moment.

Also, in v2 of the package, there is no config file to customize certain features.

Finally, in the end, is there any chance of having a multiple file upload options in this version upgrade?

**Comment by awcodes** [comment]
hey @umangapathak999 

This is just a working repo. You should be using https://gitbub.com/awcodes/filament-curator.

I will be archiving this repo shortly.

All customization in v2 is handled through the Curator facade now. It's in the Readme.
